name: secrets
on: 
  push:
    branches: [main]
  pull_request:
    type: [opened, reopened, synchronize]
  workflow_dispatch:

jobs: 
  fetcg-secrets:
    runs-on: ubuntu-latest
    steps:
      - run: echo This is my secret ${{secrets.my_first_secret}}